name: Restrict merges to main

on:
    pull_request:
        branches: [main]

jobs:
    check-source:
        if: github.base_ref == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: Check source branch
              if: github.head_ref != 'develop'
              run: |
                  echo "Only develop can be merged into main"
                  exit 1
